### ISSUE TITLE
Add FAQ Section to Documentation

### ISSUE THREAD

**Issue by DidiNDexter** [Lets-code-with-us/scamwebsiteV1#107]
### ISSUE NAME

Add FAQ

### ISSUE DESCRIPTION

There is no FAQ to the current documentation making it informative, the use FAQ contributors will find it easy to navigate and provide further clarity

**Comment by Shu12388y** [comment]
@DidiNDexter  assigned

**Comment by DidiNDexter** [comment]
okay

**Comment by DidiNDexter** [comment]
Done and created a pull request @Shu12388y
