### ISSUE TITLE
missing image of team members

### ISSUE THREAD

**Issue by ritikraj2425** [Lets-code-with-us/scamwebsiteV1#108]
### ISSUE NAME

missing image of team members

### ISSUE DESCRIPTION

on the about page meet our team section there are some images missing for
<img width="1432" alt="Screenshot 2024-10-22 at 11 50 19 AM" src="https://github.com/user-attachments/assets/88f51428-daf2-438b-bc2f-2aa0450b768a">
 team members
 Please assign this issue to me

**Comment by ritikraj2425** [comment]
please assign this issue to me

**Comment by Shu12388y** [comment]
@ritikraj2425 Other contributors are working on the About page. Right now no need to change
