### ISSUE TITLE
Newsletter Form Not Submitting Email or Showing Feedback

### ISSUE THREAD

**Issue by VanshChitransh** [Lets-code-with-us/scamwebsiteV1#12]
### Description:
The newsletter form is not accepting email input and is not providing any feedback (such as a success or error message) after submission. Users are unable to register their email for the newsletter, and no confirmation or error is displayed on the screen.

### Steps to Reproduce:
1. Navigate to the page with the newsletter sign-up form.
2. Enter a valid email address in the newsletter form.
3. Click on the "Subscribe" or "Submit" button.
4. Observe the form behavior (no message is displayed, and the email is not registered).

### Expected Behavior:
- Upon entering a valid email and submitting the form, a confirmation message should appear indicating that the email has been successfully registered for the newsletter.
- If the email is invalid or there is an error, an appropriate error message should be displayed.

### Actual Behavior:
- No confirmation or error message is shown after the form submission.
- The email is not being registered for the newsletter.

### Additional Information:
- Browser: [e.g., Chrome 117.0, Firefox 119.0]
- Operating System: [e.g., Windows 11, macOS Ventura]
- Relevant code snippet (if any): 
  
![Screenshot from 2024-10-11 03-58-14](https://github.com/user-attachments/assets/3a3324ae-f473-4fb3-97a6-be7715f41d4b)

**Comment by VanshChitransh** [comment]
@kik-o I would love to work on this issue.

**Comment by Shu12388y** [comment]
@VanshChitransh Start working on the issue
