### ISSUE TITLE
Rebuilding a Readme file along with a Issue Template Form 

### ISSUE THREAD

**Issue by Megh2005** [Lets-code-with-us/scamwebsiteV1#14]
I want to make your readme file more user friendly and attractive with the use of icons and images
I will also add an issue template form using GitHub workflow and `yml` which will appear when someone is raising any issue. That form will help you to keep track of all issues in an organized format. 
Please assign me the issue with a `hacktoberfest` and `hacktoberfest-accepted` label
It will be both coding and non coding solution.

**Comment by Shu12388y** [comment]
@Megh2005 You can start working

**Comment by Megh2005** [comment]
I will give you a PR by today evening

**Comment by Shu12388y** [comment]
@Megh2005 Here is my Linkedln https://www.linkedin.com/in/shubham-paul-5a3a8a21b/
Here is my discord Id shubham_paul_999

**Comment by Megh2005** [comment]
Given a PR after updating the readme

**Comment by Shu12388y** [comment]
@Megh2005 Thanks for contributing. You can close this issue

**Comment by Shu12388y** [comment]
@Megh2005 Nice Work

**Comment by Megh2005** [comment]
@Shu12388y just do one thing 
Go to the issues section and try to create a new issue

**Comment by Shu12388y** [comment]
@Megh2005 I just created a new issue

**Comment by Megh2005** [comment]
Have you seen the form??

**Comment by Shu12388y** [comment]
@Megh2005 which form ?

**Comment by Megh2005** [comment]
![Screenshot_20241011_153455](https://github.com/user-attachments/assets/a8af4506-21bf-452e-bae0-0164c24933e9)
This one
Click on the **New Issue** button under the issues tab and then click **Get Started**

**Comment by Shu12388y** [comment]
@Megh2005 Yes

**Comment by Megh2005** [comment]
The pr is still not assigned to me
Please assign it 
As well as remove the `under review` label from the pr

**Comment by Shu12388y** [comment]
@Megh2005 I am closing this issue. You can Create new issues and start working on it.
I have merge the PR.
