### ISSUE TITLE
Add testing library like JEST

### ISSUE THREAD

**Issue by Shu12388y** [Lets-code-with-us/scamwebsiteV1#26]
### ISSUE NAME

Add testing library like JEST

### ISSUE DESCRIPTION

We don't have any testing for the front end.

### YOUR APPROACH

Use jest for testing 
Here is the reference https://medium.com/expedia-group-tech/ui-testing-with-react-testing-library-and-jest-f3bd9d4ec2ea
Write the test only for the home page

### YOUR NAME

Shubham

### YOUR GITHUB PROFILE URL

https://github.com/shu12388y/

**Comment by Reterics** [comment]
Hi @Shu12388y ,

I am happy to join adding JEST to the project. Can you assign it to me?

**Comment by Shu12388y** [comment]
@Reterics Assigned 
Only add the test for the home page only for now

**Comment by Reterics** [comment]
Thank you, I created a **PR** for this Issue. To have a better example i created the Home page along with the Hero component.

Can you connect the PR with the Issue if the solution is fine for you?

**Comment by Shu12388y** [comment]
@Reterics We will issue more issues to you writing more jest test 
Thanks for your contribution
