### ISSUE TITLE
The like api is not working working properly

### ISSUE THREAD

**Issue by Shu12388y** [Lets-code-with-us/scamwebsiteV1#28]
### ISSUE NAME

The like api is not working working properly

### ISSUE DESCRIPTION

The like API is not working properly

### YOUR APPROACH

Check the API and data model of like if required, and change it, if there is an error

### YOUR NAME

Shubham

### YOUR GITHUB PROFILE URL

https://github.com/shu12388y/

**Comment by harshalranjhani** [comment]
can you please assign this issue to me?

**Comment by Shu12388y** [comment]
@harshalranjhani Assigned
