### ISSUE TITLE
Improve the UI/layout of login page

### ISSUE THREAD

**Issue by Shu12388y** [Lets-code-with-us/scamwebsiteV1#29]
### ISSUE NAME

Improve the UI/layout of login page

### ISSUE DESCRIPTION

The login UI/layout is not good. It needs some padding and margin. So make it responsive

![Screenshot (21)](https://github.com/user-attachments/assets/27a6ffaa-56a3-4b3c-afb9-5ef68eb24e7e)

### YOUR APPROACH

Use tailwind class to improve the UI/layout of the page

### YOUR NAME

Shubham

### YOUR GITHUB PROFILE URL

https://github.com/shu12388y/

**Comment by adilkadivala** [comment]
hey @Shu12388y  i want to work on it, let assign it me

**Comment by Shu12388y** [comment]
@adilkadivala Assigned
