### ISSUE TITLE
Password issue

### ISSUE THREAD

**Issue by mayank-0789** [Lets-code-with-us/scamwebsiteV1#49]
# Password Requirements

To ensure the security of your account, please follow these guidelines when creating a password:

- Your password must be **at least 8 characters long**.
- It is recommended that your password includes:
  - Uppercase and lowercase letters
  - Numbers
  - Special characters (e.g., `@`, `#`, `!`, etc.)

**Example:**
- Valid password: `SecureP@ssw0rd`
- Invalid password: `abc123`

Following these guidelines will help protect your account from unauthorized access.

Your website is also accepting  3 digit password

**Comment by mayank-0789** [comment]
Hey please assign this issue to me

**Comment by gt951436** [comment]
@avinash201199 assign this to me please

**Comment by Shu12388y** [comment]
@mayank-0789  @gt951436 This issue is under review. Please close this issue. The PR is already created.
