### ISSUE TITLE
Enhance Navbar: Make Sticky and Improve Appearance

### ISSUE THREAD

**Issue by Abhi-Jeeet** [Lets-code-with-us/scamwebsiteV1#54]
### ISSUE NAME

Enhance Navbar

### ISSUE DESCRIPTION

The current navbar is basic and lacks modern design features. This issue aims to enhance the user experience by making the navbar sticky at the top of the page and improving its overall appearance.
Sample Pic:-

![Screenshot 2024-10-12 195442](https://github.com/user-attachments/assets/63a45072-8989-47b7-9602-e64e12da9ecb)

Please assign it to me and mark it as hactoberfest.

**Comment by Shu12388y** [comment]
@Abhi-Jeeet, Another contributor has already created this issue. Create a new issue.
