### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by Shu12388y** [Lets-code-with-us/scamwebsiteV1#62]
### ISSUE NAME

Update the readme

### ISSUE DESCRIPTION

New build commands are added in the pcakge.json file to update the commands in the readme

**Comment by Shu12388y** [comment]
@Shivansh-22866 Assigned

Check out the package.json file and add the npm scripts

**Comment by Shivansh-22866** [comment]
Hey @Shu12388y, I have made the PR for the updated readme file. Kindly review it as soon as possible
