### ISSUE TITLE
Add a cron job api that send email to the register user about the new blogs published  

### ISSUE THREAD

**Issue by Shu12388y** [Lets-code-with-us/scamwebsiteV1#65]
### ISSUE NAME

Add a cron job api that send email to the register user about the new blogs published  

### ISSUE DESCRIPTION

Here are the docs https://vercel.com/docs/cron-jobs
Every Wednesday mail every signup user about the new blogs

**Comment by shashi-sah2003** [comment]
Hey @Shu12388y I have worked with cron jobs pls assign me this issue
thanks

**Comment by Shu12388y** [comment]
@shashi-sah2003  assigned

**Comment by shashi-sah2003** [comment]
@Shu12388y should I make the changes in the src/utils/sendMail.ts file or should I make my separate file for this?

**Comment by Shu12388y** [comment]
@shashi-sah2003 make the separate file

**Comment by shashi-sah2003** [comment]
@Shu12388y I have raised a PR https://github.com/Lets-code-with-us/scamwebsiteV1/pull/88
pls review and let me know if there is anything more to be done
thanks
