### ISSUE TITLE
Change Color of Active Tab Buttons on Navigation Bar

### ISSUE THREAD

**Issue by PragyaTripathi990** [Lets-code-with-us/scamwebsiteV1#68]
### ISSUE NAME

improve UI features

### ISSUE DESCRIPTION

I want the color of the active tab buttons on the navigation bar to change so users can easily see which tab they are currently on. This will improve navigation and make the user experience clearer.

Underlining the active tab button instead of changing its color.
Adding a background highlight to the active tab.
<img width="1468" alt="Screenshot 2024-10-13 at 7 08 26 AM" src="https://github.com/user-attachments/assets/1f0f1c9e-e1c3-43de-8313-326d355fdf07">

**Comment by shashi-sah2003** [comment]
hey @PragyaTripathi990 pls assign me this issue
thanks

**Comment by Shu12388y** [comment]
@shashi-sah2003 Somebody is working the navbar.

**Comment by itsharshitrwt** [comment]
Is the issue still up, can i work on this??
