### ISSUE TITLE
[Enhance] Add better and larger icons for 'Scam Types' section, along with its title

### ISSUE THREAD

**Issue by ShreeluSantosh** [Lets-code-with-us/scamwebsiteV1#75]
### ISSUE NAME

Better and larger icons and title for 'Scam Types' section

### ISSUE DESCRIPTION

![image](https://github.com/user-attachments/assets/1b190831-bf0b-4397-9611-2befa4b845ad)

In the above screenshot of "Scam Types" section, the title is missing. Also, the logos for each scam type are inconsistent.

**PROPOSED SOLUTION**

Use Font Awesome library to replace the existing SVG icons with new, bolder and consistent icons

**Comment by Shu12388y** [comment]
@ShreeluSantosh assigned
