### ISSUE TITLE
Enhance the Navbar link by adding the background color on hover

### ISSUE THREAD

**Issue by 0APOCALYPSE0** [Lets-code-with-us/scamwebsiteV1#79]
### ISSUE NAME

improving navbar link styling

### ISSUE DESCRIPTION

Currently, If we hover over the navbar link, the link style does not change, So, I have improved the user experience by adding the hover effect to the links.

**Comment by Shu12388y** [comment]
@0APOCALYPSE0 One contributor is working on this issue. I will update you
