### ISSUE TITLE
Add ZOD validation in the backend API

### ISSUE THREAD

**Issue by Shu12388y** [Lets-code-with-us/scamwebsiteV1#9]

**Comment by Nazim9945** [comment]
Hi @Shu12388y  have a look on my PR and pls label this issue under hacktoberfest-accepted.

**Comment by Shu12388y** [comment]
@Nazim9945 Don't create PR untill issue is assign to you

**Comment by Shu12388y** [comment]
@Nazim9945 Check the review and add it to your PR

**Comment by Shu12388y** [comment]
@Nazim9945 Thanks for your contribution
